### PR TITLE
Bugfix volalite functions#47

### LINKED ISSUE #47: VOLATILE functions accepted in non-partition key qual. clauses
This is pretty problematic. `pg_shard` only checks for constant expressions in clauses involving the partition key, meaning anything goes in other clauses. Take this table:

```sql
CREATE TABLE limit_orders (
  id bigint PRIMARY KEY,
  symbol text NOT NULL,
  bidder_id bigint NOT NULL,
  placed_at timestamp NOT NULL,
  kind order_side NOT NULL,
  limit_price decimal NOT NULL DEFAULT 0.00 CHECK (limit_price >= 0.00)
);

SELECT master_create_distributed_table('limit_orders', 'id');
```

Trying to `INSERT` into this table using non-constant expressions will fail:

```sql
INSERT INTO limit_orders VALUES (2036, 'GOOG', 5634, now(), 'buy', random());
# ERROR:  cannot plan sharded modification containing values which are not constants or constant expressions
```

But `pg_shard` happily accepts a `random()` appearing in a `DELETE` command's clauses:

```sql
DELETE FROM limit_orders WHERE id = 246 AND bidder_id = (random() * 1000);
```

I believe the root cause here is the fact that `UPDATE` and `DELETE` share code with `SELECT`. It's _probably_ OK that `SELECT` accepts `random()` in its `WHERE` clause: for `SELECT` queries, we need only execute on a single replica, so the fact that calls to `random()` on two replicas will return different values is irrelevant.

But for `DELETE` and `UPDATE` this is an issue: replicas will diverge. We should either always require constant expressions or work towards evaluating function calls on the master before executing remote portions of the plan.

### PR DESCRIPTION
**Pull request by onderkalaci**
This pull request prevents WHERE clause statements to have VOLATILE or MUTABLE functions.

Fixes #47

**Review tasks**

  - [x] Fix comment in test
  - [x] Rework area that used ternary expression
  - [x] Remove call to `contain_volatile_functions`
  - [x] Add test with mutable but not volatile function such as `current_timestamp`

### CODE REVIEW

**Comment by onderkalaci** [comment]
@jasonmp85 I think we can do a similar change for [this line](https://github.com/citusdata/pg_shard/blob/develop/pg_shard.c#L530). In other words, instead of checking 
```c
!IsA(targetEntry->expr, Const)
```
We can do something like:
```c
contain_mutable_functions((targetEntry->exp) ||
	contain_volatile_functions((targetEntry->exp))	
```
But, since the issue only considers QUALs, I didn't want to do that here.

File: pg_shard.c [hunk 1]
```diff
@@ -393,7 +393,9 @@ ErrorIfQueryNotSupported(Query *queryTree)
 	bool hasValuesScan = false;
 	uint32 queryTableCount = 0;
 	bool hasNonConstTargetEntryExprs = false;
+	bool hasNonConstQualExprs = false;
 	bool specifiesPartitionValue = false;
+	Node *whereClause = NULL;
```
Comment (jasonmp85) [inline pg_shard.c]: This variable can have its scope reduced… please put it inside the `if (commandType == CMD_INSERT || commandType == CMD_UPDATE ||…` block.

File: pg_shard.c [hunk 2]
```diff
@@ -537,9 +539,17 @@ ErrorIfQueryNotSupported(Query *queryTree)
 				specifiesPartitionValue = true;
 			}
 		}
+
+		whereClause = ((queryTree->jointree == NULL) ?
```
Comment (jasonmp85) [inline pg_shard.c]: We _seldom_ (never, maybe?) use the ternary operator in our style. I'd say this is more idiomatic CitusDB style:

```c
FromExpr *joinTree = query->jointree;
if (joinTree != NULL && contain_volatile_functions(joinTree->quals))
{
    hasNonConstQualExprs = true;
}
```

File: pg_shard.c [hunk 3]
```diff
@@ -537,9 +539,17 @@ ErrorIfQueryNotSupported(Query *queryTree)
...
+					   NULL : queryTree->jointree->quals);
+		if (contain_mutable_functions(whereClause) ||
+			contain_volatile_functions(whereClause))
```
Comment (jasonmp85) [inline pg_shard.c]: I think it's sufficient to call `contain_mutable_function` here: anything that is `VOLATILE` is also not `IMMUTABLE`, so this is redundant.

File: expected/modifications.out.tmpl [hunk 4]
```diff
@@ -77,6 +77,9 @@ ERROR:  cannot plan sharded modification containing values which are not constan
 -- commands with expressions that cannot be collapsed are unsupported
 INSERT INTO limit_orders VALUES (2036, 'GOOG', 5634, now(), 'buy', random());
 ERROR:  cannot plan sharded modification containing values which are not constants or constant expressions
+-- commands with mutable or volitale functions
```
Comment (jasonmp85) [inline expected/modifications.out.tmpl]: Misspelled, but replace with `commands with mutable functions in their quals`

**Comment by jasonmp85** [comment]
@onderkalaci this looks good and after the small style changes (and removing the redundant call), it's a :shipit:.

**Comment by jasonmp85** [comment]
@onderkalaci on the topic of

**Comment by jasonmp85** [comment]
Accidentally closed, sorry!

**Comment by jasonmp85** [comment]
@onderkalaci on the topic of `!IsA(targetEntry->expr, Const)`, we already know any function calls we see in the target list _must_ be mutable. This is because we have already called the `standard_planner` on the query. That in turn calls `eval_const_expressions`, which eagerly replaces any immutable functions with their output (this also applies to the quals; for instance, doing an `UPDATE … WHERE foo = (1 + 1)` becomes `UPDATE … WHERE foo = 2`).

So for target lists, we only accept constants, but for quals, there might be a column reference (LHS), operator, and value (RHS). In that case, the standard planner may have collapsed the RHS to a constant (if, as above it's something like `1+1`), but the operator call is still there. But e.g. `=` is `IMMUTABLE` so it needs to make it through.

**Comment by jasonmp85** [comment]
So I guess I'm saying the walker is overkill for the target list but is needed for the quals, so what we have here is now complete.

File: pg_shard.c (hunk 1 above)
Comment (jasonmp85) [inline pg_shard.c]: Instead of `whereClause`, I think you just need to declare `FromExpr *joinTree;` inside the `if` block.

File: sql/modifications.sql [hunk 5]
```diff
@@ -54,6 +54,9 @@ INSERT INTO limit_orders VALUES (random() * 100, 'ORCL', 152, '2011-08-25 11:50:
 -- commands with expressions that cannot be collapsed are unsupported
 INSERT INTO limit_orders VALUES (2036, 'GOOG', 5634, now(), 'buy', random());
 
+-- commands with mutable or volitale functions 
+DELETE FROM limit_orders WHERE id = 246 AND bidder_id = (random() * 1000);
+
```
Comment (jasonmp85) [inline sql/modifications.sql]: Can you add another test with a function which is stable but not mutable? That way we'll have one test that checks `VOLATILE` and another checking `STABLE`.

**Comment by jasonmp85** [comment]
Added checklist up to. Fix and submit the changes and I'll merge tomorrow if all looks good.

**Comment by onderkalaci** [comment]
@jasonmp85 all your comments make sense and I applied the changes.

**Comment by jasonmp85** [comment]
Looks good. Merging.
